org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true

GROUP=com.cocosw
POM_ARTIFACT_ID=formfiller
VERSION_NAME=2.0.0
POM_NAME=FormFiller
POM_DESCRIPTION=Android helper library to populate form fields with predefined data set
POM_INCEPTION_YEAR=2020
POM_URL=https://github.com/soarcn/FormFiller
POM_SCM_URL=https://github.com/soarcn/FormFiller
POM_SCM_CONNECTION=scm:git:git://github.com/soarcn/FormFiller.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/soarcn/FormFiller.git
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=soarcn
POM_DEVELOPER_NAME=Kai Wang
